version: 0.2

proxy:
  upload-artifacts: yes
  logs: yes

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
  pre_build:
    commands:
      - echo prebuild
  build:
    commands:
      - ./gradlew build
      - echo build
  post_build:
    commands:
      - echo postbuild
artifacts:
  files:
    - ./build/libs/demoWarGradle-0.0.1-SNAPSHOT.war